#!/bin/bash

##D:XXXI.XII.MMXVIII.###################################S.T.F.C.##
#                ,___,
#               n o,0 ne          "Sumerian Time Format Convertor"
#  Powered by:   /)#)
#================="="============================================
hrs=$(date +%H)                                     #hours
min=$(date +%M)                                     #minutes
sec=$(date +%S)                                     #seconds
nas=$(date +%N)                                     #nanoseconds
dom=$(date +%d)                                     #day of month
dow=$(date +%w)                                     #day of week
won=$(date +%U)                                     #no. of week
mon=$(date +%m)                                     #no. of month
doy=$(date +%j)                                     #day of year
noy=$(date +%Y)                                     #no. of year
dim=$(((10#$hrs * 60) + 10#$min))                   #day expressed in minutes 
dis=$(((10#$dim * 60) + 10#$sec))                   #day expressed in seconds
did=$((10#$dis / 240))                              #day expressed in degree (planet pole-revolution)
yim=$(((10#$doy * 1440) + 10#$dim))                 #year expressed in minutes
yis=$(((10#$doy * 86400) + 10#$dis))                #year expressed in seconds
yih=$(((10#$doy * 24) + 10#$hrs))                   #year expressed in hours
# ================================================================
diss=$((10#$dis / 2))                               #day expressed in sumerian seconds
dism=$((10#$diss / 60))                             #day expressed in Sumerian Minutes
dish=$((10#$dism / 60))                             #day expressed in sumerian Hours &DAANA&
sm=$((10#$dism - (10#$dish * 60)))                  #Sumerian minutes
ss=$((10#$diss - (10#$dism * 60)))                  #Sumerian seconds
# ================================================================
if [ $dish = 1 ]; then
echo " "
echo "                                                      "
echo " Sumerian Time                                        "
echo " [ $dish°:$sm':$ss\"]                                 "
echo "                                      POWERED BY: no0ne "
echo " Earth Rotation                                       "
echo " [ $did° ]                                            "
echo "                         XII.                         "
echo "                        [ 0°]                         "
echo "                                                      "
echo "                        night                         "
echo "                        SPACE                         "
echo "                          ▄                           "   
echo "    I.  ■ [$did°]      X     ■       [330°]     .XI   "
echo "   II.     [060°]    ■         ■     [300°]     .X    "
echo "  III.     [090°]   ■     +     ■    [270°]     .IX   "
echo "   IV.     [120°]    ■         ■     [240°]     .VIII " 
echo "    V.     [150°]      ■     ■       [210°]     .VII  "
echo "                          ▀                           "
echo "                         SUN                          "
echo "                         day                          "
echo "                                                      "
echo "                        [180°]                        " 
echo "                          VI.                         "
echo " Universal Time                      Day of Year      "
echo " [ $hrs:$min:$sec ]                         [ $doy ]  "
echo "                                                      "
fi
#
if [ $dish = 2 ]; then
echo " "    
echo "                                                      "
echo " Sumerian Time                                        "
echo " [ $dish°:$sm':$ss\"]                                 "
echo "                                      POWERED BY: no0ne "
echo " Earth Rotation                                       "
echo " [ $did° ]                                            "
echo "                         XII.                         "
echo "                        [ 0°]                         "
echo "                                                      "
echo "                        night                         "
echo "                        SPACE                         "
echo "                          ▄                           "   
echo "    I.     [030°]      ■     ■       [330°]     .XI   "
echo "   II.  ■ [$did°]    X         ■     [300°]     .X    "
echo "  III.     [090°]   ■     +     ■    [270°]     .IX   "
echo "   IV.     [120°]    ■         ■     [240°]     .VIII " 
echo "    V.     [150°]      ■     ■       [210°]     .VII  "
echo "                          ▀                           "
echo "                         SUN                          "
echo "                         day                          "
echo "                                                      "
echo "                        [180°]                        " 
echo "                          VI.                         "
echo " Universal Time                      Day of Year      "
echo " [ $hrs:$min:$sec ]                         [ $doy ]  "
echo "                                                      "
fi
#
if [ $dish = 3 ]; then
echo " "
echo "                                                      "
echo " Sumerian Time                                        "
echo " [ $dish°:$sm':$ss\"]                                 "
echo "                                      POWERED BY: no0ne "
echo " Earth Rotation                                       "
echo " [ $did° ]                                            "
echo "                         XII.                         "
echo "                        [ 0°]                         "
echo "                                                      "
echo "                        night                         "
echo "                        SPACE                         "
echo "                          ▄                           "   
echo "    I.     [030°]      ■     ■       [330°]     .XI   "
echo "   II.     [060°]    ■         ■     [300°]     .X    "
echo "  III.  ■ [$did°]   X     +     ■    [270°]     .IX   "
echo "   IV.     [120°]    ■         ■     [240°]     .VIII " 
echo "    V.     [150°]      ■     ■       [210°]     .VII  "
echo "                          ▀                           "
echo "                         SUN                          "
echo "                         day                          "
echo "                                                      "
echo "                        [180°]                        " 
echo "                          VI.                         "
echo " Universal Time                      Day of Year      "
echo " [ $hrs:$min:$sec ]                         [ $doy ]  "
echo "                                                      "
fi
#
if [ $dish = 4 ]; then
echo " "
echo "                                                      "
echo " Sumerian Time                                        "
echo " [ $dish°:$sm':$ss\"]                                 "
echo "                                      POWERED BY: no0ne "
echo " Earth Rotation                                       "
echo " [ $did° ]                                            "
echo "                         XII.                         "
echo "                        [ 0°]                         "
echo "                                                      "
echo "                        night                         "
echo "                        SPACE                         "
echo "                          ▄                           "   
echo "    I.     [030°]      ■     ■       [330°]     .XI   "
echo "   II.     [060°]    ■         ■     [300°]     .X    "
echo "  III.     [090°]   ■     +     ■    [270°]     .IX   "
echo "   IV.  ■ [$did°]    X         ■     [240°]     .VIII " 
echo "    V.     [150°]      ■     ■       [210°]     .VII  "
echo "                          ▀                           "
echo "                         SUN                          "
echo "                         day                          "
echo "                                                      "
echo "                        [180°]                        " 
echo "                          VI.                         "
echo " Universal Time                      Day of Year      "
echo " [ $hrs:$min:$sec ]                         [ $doy ]  "
echo "                                                      "
fi
#
if [ $dish = 5 ]; then
echo " "
echo "                                                      "
echo " Sumerian Time                                        "
echo " [ $dish°:$sm':$ss\"]                                 "
echo "                                      POWERED BY: no0ne "
echo " Earth Rotation                                       "
echo " [ $did° ]                                            "
echo "                         XII.                         "
echo "                        [ 0°]                         "
echo "                                                      "
echo "                        night                         "
echo "                        SPACE                         "
echo "                          ▄                           "   
echo "    I.     [030°]      ■     ■       [330°]     .XI   "
echo "   II.     [060°]    ■         ■     [300°]     .X    "
echo "  III.     [090°]   ■     +     ■    [270°]     .IX   "
echo "   IV.     [120°]    X         ■     [240°]     .VIII " 
echo "    V.  ■ [$did°]      ■     ■       [210°]     .VII  "
echo "                          ▀                           "
echo "                         SUN                          "
echo "                         day                          "
echo "                                                      "
echo "                        [180°]                        " 
echo "                          VI.                         "
echo " Universal Time                      Day of Year      "
echo " [ $hrs:$min:$sec ]                         [ $doy ]  "
echo "                                                      "
fi
#
if [ $dish = 6 ]; then
echo " "
echo "                                                      "
echo " Sumerian Time                                        "
echo " [ $dish°:$sm':$ss\"]                                 "
echo "                                      POWERED BY: no0ne "
echo " Earth Rotation                                       "
echo " [ $did° ]                                            "
echo "                         XII.                         "
echo "                        [ 0°]                         "
echo "                                                      "
echo "                        night                         "
echo "                        SPACE                         "
echo "                          ▄                           "   
echo "    I.     [030°]      ■     ■       [330°]     .XI   "
echo "   II.     [060°]    ■         ■     [300°]     .X    "
echo "  III.     [090°]   ■     +     ■    [270°]     .IX   "
echo "   IV.     [120°]    ■         ■     [240°]     .VIII " 
echo "    V.     [150°]      ■     ■       [210°]     .VII  "
echo "                          X                           "
echo "                         SUN                          "
echo "                         day                          "
echo "                          ■                           "
echo "                        [$did°]                       " 
echo "                          VI.                         "
echo " Universal Time                      Day of Year      "
echo " [ $hrs:$min:$sec ]                         [ $doy ]  "
echo "                                                      "
fi
#
if [ $dish = 7 ]; then
echo " "
echo "                                                      "
echo " Sumerian Time                                        "
echo " [ $dish°:$sm':$ss\"]                                 "
echo "                                      POWERED BY: no0ne "
echo " Earth Rotation                                       "
echo " [ $did° ]                                            "
echo "                         XII.                         "
echo "                        [ 0°]                         "
echo "                                                      "
echo "                        night                         "
echo "                        SPACE                         "
echo "                          ▄                           "   
echo "    I.     [030°]      ■     ■       [330°]     .XI   "
echo "   II.     [060°]    ■         ■     [300°]     .X    "
echo "  III.     [090°]   ■     +     ■    [270°]     .IX   "
echo "   IV.     [120°]    ■         ■     [240°]     .VIII " 
echo "    V.     [150°]      ■     X        [$did°] ■  .VII "
echo "                          ▀                           "
echo "                         SUN                          "
echo "                         day                          "
echo "                                                      "
echo "                        [180°]                        " 
echo "                          VI.                         "
echo " Universal Time                      Day of Year      "
echo " [ $hrs:$min:$sec ]                         [ $doy ]  "
echo "                                                      "
fi
#
if [ $dish = 8 ]; then
echo " "
echo "                                                      "
echo " Sumerian Time                                        "
echo " [ $dish°:$sm':$ss\"]                                 "
echo "                                      POWERED BY: no0ne "
echo " Earth Rotation                                       "
echo " [ $did° ]                                            "
echo "                         XII.                         "
echo "                        [ 0°]                         "
echo "                                                      "
echo "                        night                         "
echo "                        SPACE                         "
echo "                          ▄                           "   
echo "    I.     [030°]      ■     ■       [330°]     .XI   "
echo "   II.     [060°]    ■         ■     [300°]     .X    "
echo "  III.     [090°]   ■     +     ■    [270°]     .IX   "
echo "   IV.     [120°]    ■         X      [$did°] ■  .VIII" 
echo "    V.     [150°]      ■     ■       [210°]     .VII  "
echo "                          ▀                           "
echo "                         SUN                          "
echo "                         day                          "
echo "                                                      "
echo "                        [180°]                        " 
echo "                          VI.                         "
echo " Universal Time                      Day of Year      "
echo " [ $hrs:$min:$sec ]                         [ $doy ]  "
echo "                                                      "
fi
#
if [ $dish = 9 ]; then
echo " "
echo "                                                      "
echo " Sumerian Time                                        "
echo " [ $dish°:$sm':$ss\"]                                 "
echo "                                      POWERED BY: no0ne "
echo " Earth Rotation                                       "
echo " [ $did° ]                                            "
echo "                         XII.                         "
echo "                        [ 0°]                         "
echo "                                                      "
echo "                        night                         "
echo "                        SPACE                         "
echo "                          ▄                           "   
echo "    I.     [030°]      ■     ■       [330°]     .XI   "
echo "   II.     [060°]    ■         ■     [300°]     .X    "
echo "  III.     [090°]   ■     +     X     [$did°] ■  .IX  "
echo "   IV.     [120°]    ■         ■     [240°]     .VIII " 
echo "    V.     [150°]      ■     ■       [210°]     .VII  "
echo "                          ▀                           "
echo "                         SUN                          "
echo "                         day                          "
echo "                                                      "
echo "                        [180°]                        " 
echo "                          VI.                         "
echo " Universal Time                      Day of Year      "
echo " [ $hrs:$min:$sec ]                         [ $doy ]  "
echo "                                                      "
fi
#
if [ $dish = 10 ]; then
echo " "
echo "                                                      "
echo " Sumerian Time                                        "
echo " [ $dish°:$sm':$ss\"]                                 "
echo "                                      POWERED BY: no0ne "
echo " Earth Rotation                                       "
echo " [ $did° ]                                            "
echo "                         XII.                         "
echo "                        [ 0°]                         "
echo "                                                      "
echo "                        night                         "
echo "                        SPACE                         "
echo "                          ▄                           "   
echo "    I.     [030°]      ■     ■       [330°]     .XI   "
echo "   II.     [060°]    ■         X      [$did°] ■  .X   "
echo "  III.     [090°]   ■     +     ■    [270°]     .IX   "
echo "   IV.     [120°]    ■         ■     [240°]     .VIII " 
echo "    V.     [150°]      ■     ■       [210°]     .VII  "
echo "                          ▀                           "
echo "                         SUN                          "
echo "                         day                          "
echo "                                                      "
echo "                        [180°]                        " 
echo "                          VI.                         "
echo " Universal Time                      Day of Year      "
echo " [ $hrs:$min:$sec ]                         [ $doy ]  "
echo "                                                      "
fi
#
if [ $dish = 11 ]; then
echo " "
echo "                                                                              "
echo " Sumerian Time                                        "
echo " [ $dish°:$sm':$ss\"]                                 "
echo "                                      POWERED BY: no0ne "
echo " Earth Rotation                                       "
echo " [ $did° ]                                            "
echo "                         XII.                         "
echo "                        [ 0°]                         "
echo "                                                      "
echo "                        night                         "
echo "                        SPACE                         "
echo "                          ▄                           "   
echo "    I.     [030°]      ■     X        [$did°] ■  .XI  "
echo "   II.     [060°]    ■         ■     [300°]     .X    "
echo "  III.     [090°]   ■     +     ■    [270°]     .IX   "
echo "   IV.     [120°]    ■         ■     [240°]     .VIII " 
echo "    V.     [150°]      ■     ■       [210°]     .VII  "
echo "                          ▀                           "
echo "                         SUN                          "
echo "                         day                          "
echo "                                                      "
echo "                        [180°]                        " 
echo "                          VI.                         "
echo " Universal Time                      Day of Year      "
echo " [ $hrs:$min:$sec ]                         [ $doy ]  "
echo "                                                      "
fi
#
if [ $dish = 0 ]; then
echo " "
echo "                                                                              "
echo " Sumerian Time                                        "
echo " [ $dish°:$sm':$ss\"]                                 "
echo "                                      POWERED BY: no0ne "
echo " Earth Rotation                                       "
echo " [ $did° ]                                            "
echo "                         XII.                         "
echo "                        [$did°]                       "
echo "                          ■                           "
echo "                        night                         "
echo "                        SPACE                         "
echo "                          X                           "   
echo "    I.     [030°]      ■     ■       [330°]     .XI   "
echo "   II.     [060°]    ■         ■     [300°]     .X    "
echo "  III.     [090°]   ■     +     ■    [270°]     .IX   "
echo "   IV.     [120°]    ■         ■     [240°]     .VIII " 
echo "    V.     [150°]      ■     ■       [210°]     .VII  "
echo "                          ▀                           "
echo "                         SUN                          "
echo "                         day                          "
echo "                                                      "
echo "                        [180°]                        " 
echo "                          VI.                         "
echo " Universal Time                      Day of Year      "
echo " [ $hrs:$min:$sec ]                         [ $doy ]  "
echo "                                                      "
fi